services:
  keycloak_server:
    image:  quay.io/keycloak/keycloak:25.0
    container_name: keycloak
    command:  start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_keycloak
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: horatz
      KC_DB_PASSWORD: s3cr3t
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: s3cr3t
      KEYCLOAK_IMPORT: 
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/certs/localhostcert.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/certs/localhostkey.pem
      DEBUG: 'true'
      DEBUG_PORT: '*:8443'
      KC_LOG_LEVEL: INFO,de.keycloak:debug
    ports:
      - "8080:8080"
      - "8843:8443"
    depends_on:
      postgres_keycloak:
        condition: service_healthy
    volumes:
      - ./certs:/opt/keycloak/certs
      - ./import/realm-import.json:/opt/keycloak/data/import/realm-import.json
    networks:
      - keycloak_network

  postgres_keycloak:
    image: postgres:16.0
    container_name: postgresdb
    command: postgres -c 'max_connections=200'
    restart: always
    environment:
      POSTGRES_USER: "horatz"
      POSTGRES_PASSWORD: "s3cr3t"
      POSTGRES_DB: "keycloak"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "exit 0"
    networks:
      - keycloak_network


volumes:
  postgres-data:
networks:
  keycloak_network:
    driver: bridge




     

