services:
  keycloak_server:
    image:  quay.io/keycloak/keycloak:25.0
    container_name: keycloak
    command:  ${COMMAND}
    environment:
      KC_DB: ${KC_DB}
      KC_DB_URL_HOST: ${KC_DB_URL_HOST}
      KC_DB_URL_DATABASE: ${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/certs/localhostcert.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/certs/localhostkey.pem
    ports:
      - "8080:8080"
      - "8843:8443"
    depends_on:
      postgres_keycloak:
        condition: service_healthy
    volumes:
      - ./certs:/opt/keycloak/certs
    networks:
      - keycloak_network

  postgres_keycloak:
    image: postgres:16.0
    container_name: postgresdb
    command: postgres -c 'max_connections=200'
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "exit 0"
    networks:
      - keycloak_network


volumes:
  postgres-data:
networks:
  keycloak_network:
    driver: bridge




     

