@baseUrl = {{$dotenv KEYCLOAK_URL}}
@KeycloakNetAuthenticationApiHostAddress = https://localhost:7194
@realm = Test
@fakerealm = dev
@client_secret = {{$dotenv CLIENT_SECRET}}
@fakeclientsecret = {{$dotenv FAKE_CLIENT_SECRET}}
@client_name = maui-client
@username = hg@g.com
@password = s3cr3te
@_username = hor
@_password = s3cr3t

@fake_password = s3cr3t

### Login user
# @name user_token_request
POST {{baseUrl}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id={{client_name}}&client_secret={{client_secret}}&username={{_username}}&password={{_password}}



### Login user
# @name user_token_request
POST {{baseUrl}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id={{client_name}}&client_secret={{client_secret}}&username={{username}}&password={{password}}

#### response
@access_token = {{user_token_request.response.body.access_token}}
@refresh_token = {{user_token_request.response.body.refresh_token}}

# @name user_token_request_fake_client
POST {{baseUrl}}/realms/{{fakerealm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id={{client_name}}&client_secret={{fakeclientsecret}}&username={{username}}&password={{fake_password}}

#### response
@fake_access_token = {{user_token_request_fake_client.response.body.access_token}}
@fake_refresh_token = {{user_token_request_fake_client.response.body.refresh_token}}


### Check Api access
GET  {{KeycloakNetAuthenticationApiHostAddress}}/api/authenticate
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Check Api access
GET  {{KeycloakNetAuthenticationApiHostAddress}}/api/authorize
Content-Type: application/json
Authorization: Bearer {{access_token}}


### 
GET  {{KeycloakNetAuthenticationApiHostAddress}}/api/authenticate
Content-Type: application/json
Authorization: Bearer {{fake_access_token}}