# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  LOCAL_CERT: ${{secrets.LOCAL_CERT}}
  LOCAL_KEY: ${{secrets.LOCAL_KEY}}
  CERT: ${{secrets.CERT}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Add Certs
      run: |
        sudo echo $CERT | base64 --decode > cert.crt | sudo cp cert.crt /usr/local/share/ca-certificates
        sudo update-ca-certificates
        echo "Added and trusted dev certificate"
      continue-on-error: false
    - name: Make dir Certs
      run: |
        cd ./tests/Keycloak.Net.Authentication.Test/Integration/
        mkdir Certs 
        echo "certs folder created for Keycloak.Net.Authentication.Test"
      continue-on-error: false
    - name: Retrieve certs files
      run: |
         cd ./tests/Keycloak.Net.Authentication.Test/Integration/Certs/
         echo $LOCAL_CERT | base64 --decode > cert.pem     
         echo $LOCAL_KEY | base64 --decode > key.key 
         echo "Added certs to Keycloak.Net.Authentication.Test"
      continue-on-error: false
    - name: Make dir Certs
      run: |
        cd ./tests/Keycloak.Net.User.Api.Tests/Integration/
        mkdir Certs 
        echo "certs folder created for Keycloak.Net.User.Api.Tests"
      continue-on-error: false
    - name: Retrieve certs files
      run: |
         cd ./tests/Keycloak.Net.User.Api.Tests/Integration/Certs/
         echo $LOCAL_CERT | base64 --decode > cert.pem     
         echo $LOCAL_KEY | base64 --decode > key.key 
         echo "Added certs to Keycloak.Net.User.Api.Tests"
      continue-on-error: false
#    - name: Install Docker
#      run: |
#        curl -fsSL https://get.docker.com -o get-docker.sh
#        sudo sh get-docker.sh
#      continue-on-error: false
#    - name: Install Docker Compose
#      run: |
#        sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#        sudo chmod +x /usr/local/bin/docker-compose
#        docker-compose --version
#      continue-on-error: false
#    - name: start docker 
#      run: |
#        docker-compose -f docker-compose.yml up -d

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
  
    - name: Test
      run: dotnet test --no-build --verbosity normal
