# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
#    - name: Install Docker
#      run: |
#        curl -fsSL https://get.docker.com -o get-docker.sh
#        sudo sh get-docker.sh
#      continue-on-error: false
#    - name: Install Docker Compose
#      run: |
#        sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#        sudo chmod +x /usr/local/bin/docker-compose
#        docker-compose --version
#      continue-on-error: false
    - name: start docker 
      run: |
        docker-compose -f docker-compose.yml up -d
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
  
    - name: Test
      run: dotnet test --no-build --verbosity normal
